package ba.unsa.etf.rpr.business;

import ba.unsa.etf.rpr.dao.DaoFactory;
import ba.unsa.etf.rpr.domain.Criminal;
import ba.unsa.etf.rpr.exceptions.CriminalRecordsException;

import java.time.LocalDate;

/**
 * Class that is business layer for Criminal
 * This class contains methods for checking all actions connected to adding new criminal
 */
public class CriminalManager {

    /**
     * Method that adds new criminal only if all data is correctly inserted
     * @param criminal
     * @return
     * @throws CriminalRecordsException
     */
    public static Criminal add(Criminal criminal) throws CriminalRecordsException {

        if (criminal.getFirstName().equals(null) || criminal.getLastName().equals(null) || criminal.getBirthDate() == null) {
            throw new CriminalRecordsException("All fields have to be filled!");
        }

        if (criminal.getId() != 0) {
            throw new CriminalRecordsException("ID is autogenerated!");
        }

        /*if (criminal.getBirthDate().isAfter(LocalDate.now())) {
            throw new CriminalRecordsException("Birth date is not correct");
        }*/

        try {
            return DaoFactory.criminalsDao().add(criminal);
        } catch (CriminalRecordsException e) {
            throw e;
        }
    }
}
