package ba.unsa.etf.rpr.business;

import ba.unsa.etf.rpr.dao.DaoFactory;
import ba.unsa.etf.rpr.domain.Criminal;
import ba.unsa.etf.rpr.exceptions.CriminalRecordsException;

import java.time.LocalDate;
import java.time.Period;

public class CriminalManager {

    public static Criminal add(Criminal criminal) throws CriminalRecordsException {

        if (criminal.getFirstName().equals(null) || criminal.getLastName().equals(null) || criminal.getBirthDate() == null) {
            throw new CriminalRecordsException("All fields have to be filled!");
        }

        if (criminal.getId() != 0) {
            throw new CriminalRecordsException("ID is autogenerated!");
        }

        Period intervalPeriod = Period.between(criminal.getBirthDate(), LocalDate.now());


        try {
            return DaoFactory.criminalsDao().add(criminal);
        } catch (CriminalRecordsException e) {
            throw e;
        }
    }
}
